[package]
name = "beat-detector"
description = """
beat-detector detects beats in live audio, but can also be used for post
analysis of audio data. It is a library written in Rust that is
`no_std`-compatible and doesn't need `alloc`.
"""
version = "0.2.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2024"
license = "MIT"
keywords = ["audio", "beat", "beat-detection"]
categories = ["multimedia::audio", "no-std"]
readme = "README.md"
homepage = "https://github.com/phip1611/beat-detector"
repository = "https://github.com/phip1611/beat-detector"
documentation = "https://docs.rs/beat-detector"
exclude = [
    ".editorconfig",
    ".github",
    "demo.gif",
]
rust-version = "1.88.0"

[features]
default = ["recording"]
# Beat detection on the audio input of the system. Requires std.
recording = ["dep:cpal", "dep:log"]

[[bench]]
name = "detector"
harness = false

[[example]]
name = "live-input-minimal"
required-features = ["recording"]

[[example]]
name = "live-input-visualize"
required-features = ["recording"]

[dependencies]
lowpass-filter = "0.5"

# recording
cpal = { version = "0.18", default-features = false, optional = true }
log = { version = "0.4", default-features = false, optional = true }


[dev-dependencies]
audio-visualizer = "0.7"
ctrlc = { version = "3.4", features = ["termination"] }
criterion = "0.8"
hound = "3.5"
simple_logger = "5.0"
minifb = "0.28"


[profile.dev]
# otherwise many code is too slow
# remove when using the debugger
# opt-level = 1

[profile.release]
# Trimmed to maximum performance.
#
# These changes only affects examples and tests build inside this crate but
# not libraries that use this.
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
